server:
  port: 8093
spring:
  application:
    name: gateway-global-filter
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 日志打印级别
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug