server:
  port: 8095
spring:
  application:
    name: admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  security:
    user:
      name: admin
      password: admin