server:
  port: 8094
spring:
  application:
    name: gateway-actuator
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: path_route
          uri: https://example.org
          predicates:
            - Path=/route
logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
management:
  endpoints:
    web:
      exposure:
        #  可以使用 '*' 代表全部
        include: gateway